NUM_GPUS: 1
DATALOADER:
  BATCH_SIZE: 12
  NUM_WORKERS: 4
TRAIN:
  ENABLE: False
  MAX_EPOCH: 40
TEST:
  ENABLE: True
  CHECKPOINT_PATH: 'objectformer_doc_tamper_adamw_ktp_base/checkpoints/ckpt_epoch_00031.pyth'
  THRES: 0.5
MODEL:
  MODEL_NAME: ObjectFormer
  INPLANES: 64
  PRETRAINED: "ckpt/casiav2_and_imd20_ep40_lr2.5e-4.pth"
  NUM_LAYERS: [1, 1, 3, 1]
  NUM_CHS: [96, 192, 384, 768]
  NUM_STRIDES: [1, 2, 2, 2]
  NUM_HEADS: [3, 6, 12, 24]
  NUM_PARTS: [64, 64, 64, 64]
  PATCH_SIZES: [8, 7, 7, 7]
  DROP_PATH: 0.1
  NUM_ENC_HEADS: [1, 3, 6, 12]
  NUM_CLASSES: 1
OPTIMIZER:
  OPTIMIZER_METHOD: adamw
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.0001
DATASET:
  DATASET_NAME: TamperingDataset
  ROOT_DIR: training_dataset
  TRAIN_SPLIT: train_split.txt
  VAL_SPLIT: val_split.txt
  TEST_SPLIT: test_split.txt
  RETURN_MASK: True
  IMG_SIZE: 320
  TRAIN_AUGMENTATIONS:
    COMPOSE:
      [
        Resize,
        RandomCrop,
        [
          RandomBrightnessContrast,
          HueSaturationValue,
          CLAHE
        ],
        GaussNoise,
        ImageCompression,
        Normalize
      ]
    RESIZE_PARAMS: [380, 380]
    RANDOMCROP_PARAMS: [320, 320]
    IMAGECOMPRESSION_PARAMS: [65, 80]
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
  
  TEST_AUGMENTATIONS:
    COMPOSE: [Resize, Normalize]
    RESIZE_PARAMS: [320, 320]
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]

SCHEDULER:
  SCHEDULER_TYPE: step
  DECAY_EPOCHS: 1000
  DECAY_RATE: 1.0
  WARMUP_LR: 0
  WARMUP_EPOCHS: 0

OUTPUT_DIR: 'objectformer_doc_tamper_adamw_ktp_base'