NUM_GPUS: 1
DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 4
TRAIN:
  ENABLE: True
  MAX_EPOCH: 50  # Longer training for full convergence
TEST:
  ENABLE: False
  CHECKPOINT_PATH: 'objectformer_doc_tamper_conservative/checkpoints/ckpt_epoch_00049.pyth'
  THRES: 0.5  # From threshold sweep results
MODEL:
  MODEL_NAME: ObjectFormer
  INPLANES: 64
  PRETRAINED: "./ckpt/imagenet_pre.pth"
  NUM_LAYERS: [1, 1, 3, 1]
  NUM_CHS: [96, 192, 384, 768]
  NUM_STRIDES: [1, 2, 2, 2]
  NUM_HEADS: [3, 6, 12, 24]
  NUM_PARTS: [64, 64, 64, 64]
  PATCH_SIZES: [8, 7, 7, 7]
  DROP_PATH: 0.1
  NUM_ENC_HEADS: [1, 3, 6, 12]
  NUM_CLASSES: 1

# STABLE PIXEL-LEVEL FOCUS FOR DOCUMENT DOMAIN
LOSS:
  # Balanced rebalancing - stable emphasis on localization
  LAMBDA_CLS: 0.3     # Keep detection meaningful
  LAMBDA_SEG: 2.4     # Moderate-strong emphasis on localization (8:1 ratio)
  
  DETECTION_LOSS:
    NAME: BCELossWithLogits  # Keep proven approach
    
  LOCALIZATION_LOSS:
    NAME: DiceLoss
    smooth: 0.5        # Balanced smoothing for stability
    CLASS_WEIGHT: [0.2, 2.0]  # Stable emphasis on tampered pixels

OPTIMIZER:
  OPTIMIZER_METHOD: adamw
  BASE_LR: 0.00004   # Further reduced for pixel metric stability
  WEIGHT_DECAY: 0.001
SCHEDULER:
  SCHEDULER_TYPE: cosine
  MIN_LR: 0.000006   # Maintains 5x ratio for meaningful late-stage updates
  WARMUP_LR: 0.000001
  WARMUP_EPOCHS: 0
  COOLDOWN_EPOCHS: 0
DATASET:
  DATASET_NAME: TamperingDataset
  ROOT_DIR: training_dataset
  TRAIN_SPLIT: train_split.txt
  VAL_SPLIT: val_split.txt
  TEST_SPLIT: test_split.txt
  RETURN_MASK: True
  IMG_SIZE: 512
  TRAIN_AUGMENTATIONS:
    COMPOSE:
      [
        # SELECTIVE AUGMENTATIONS FOR DOCUMENT DOMAIN
        # Balance generalization with edge preservation
        RandomBrightnessContrast,  # Light photometric variation
        HorizontalFlip,            # Safe spatial augmentation
        Resize,                    # Required for model input
        RandomCrop,                # Light spatial variation
        Normalize                  # Required preprocessing
      ]
    RESIZE_PARAMS: [564, 564]     # Slight upscale for crop variation
    RANDOMCROP_PARAMS: [512, 512] # Balanced resolution for efficiency
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]  # ImageNet normalization
  
  TEST_AUGMENTATIONS:
    COMPOSE: [Resize, Normalize]
    RESIZE_PARAMS: [512, 512]
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]

OUTPUT_DIR: 'objectformer_doc_tamper_conservative'